### ISSUE TITLE
Module version mismatch. Expected 47, got 14

### ISSUE THREAD

**Issue by SET001** [audreyt/node-webworker-threads#101]
Hi, I'm getting this error:

> /home/set/www/avalon/node_modules/webworker-threads/node_modules/bindings/bindings.js:83
>         throw e
>         ^
> 
> Error: Module version mismatch. Expected 47, got 14.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:440:18)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at bindings (/home/set/www/avalon/node_modules/webworker-threads/node_modules/bindings/bindings.js:76:44)
>     at Object.<anonymous> (/home/set/www/avalon/node_modules/webworker-threads/index.js:1:105)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)

Using node.js v 5.10.1

**Comment by audreyt** [comment]
It looks like Node 5 picked up a previously installed Node 4 module — Would you like to `npm uninstall webworker-threads` and reinstall again? Please reopen if the issue persists.

**Comment by SET001** [comment]
it does persists:

```
set@set:~/www/avalon$ npm uninstall webworker-threads --save
- bindings@1.2.1 node_modules/bindings
- nan@2.1.0 node_modules/nan
- webworker-threads@0.7.2 node_modules/webworker-threads
npm WARN avalon@0.0.1 No description
npm WARN avalon@0.0.1 No repository field.
set@set:~/www/avalon$ npm install webworker-threads --save

> webworker-threads@0.7.2 install /home/set/www/avalon/node_modules/webworker-threads
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/set/www/avalon/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BSON::BSONDeserialize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bson.cc:796:51: warning: ‘ssize_t node::DecodeBytes(v8::Local<v8::Value>, node::encoding)’ is deprecated (declared at /home/set/.node-gyp/5.10.1/include/node/node.h:317): Use DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
         intptr_t len = DecodeBytes(info[0], BINARY);
                                                   ^
../src/bson.cc:803:47: warning: ‘ssize_t node::DecodeWrite(char*, size_t, v8::Local<v8::Value>, node::encoding)’ is deprecated (declared at /home/set/.node-gyp/5.10.1/include/node/node.h:330): Use DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
         DecodeWrite(data, len, info[0], BINARY);
                                               ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BSON::BSONSerialize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bson.cc:897:73: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /home/set/.node-gyp/5.10.1/include/node/node.h:298): Use Encode(isolate, ...) [-Wdeprecated-declarations]
   Local<Value> bin_value = Encode(serialized_object, object_size, BINARY)->ToString();
                                                                         ^
  SOLINK_MODULE(target) Release/obj.target/WebWorkerThreads.node
  COPY Release/WebWorkerThreads.node
make: Leaving directory `/home/set/www/avalon/node_modules/webworker-threads/build'
avalon@0.0.1 /home/set/www/avalon
└─┬ webworker-threads@0.7.2 
  ├── bindings@1.2.1 
  └── nan@2.1.0 

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN avalon@0.0.1 No description
npm WARN avalon@0.0.1 No repository field.
set@set:~/www/avalon$ node js/server/index.js 
starting avalon server v0.0.1
======: connection from ::ffff:192.168.0.100 /#ZV8oVEoN2eiflR_mAAAA
starting anonymous session
===> User { login: 0, position: { x: 0, y: 0, z: 0 }, chunk: 'default' }
searching for chunk default
Connected correctly to dabatabase.
/home/set/www/avalon/node_modules/physijs-browserify/physi.js:393
		this._worker = new Worker( Physijs.scripts.worker || 'physijs_worker.js' );
		                   ^

ReferenceError: Worker is not defined
    at new Physijs.Scene (/home/set/www/avalon/node_modules/physijs-browserify/physi.js:393:22)
    at Server.simulation (/home/set/www/avalon/js/server/server.js:59:17)
    at Timeout._repeat (/home/set/www/avalon/js/server/server.js:68:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
set@set:~/www/avalon$ node -v
v5.10.1

```

**Comment by audreyt** [comment]
Actually it looks correctly installed. Try to add this line before `physi.js` line 393:

```js
var Worker = require('webworker-threads').Worker;
```
