### ISSUE TITLE
Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by ORESoftware** [audreyt/node-webworker-threads#109]
I got this just now, I am on node 6.2.1 and OSX:

```
/usr/local/bin/node exp.js
/Users/amills/WebstormProjects/oresoftware/suman/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/amills/WebstormProjects/oresoftware/suman/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/amills/WebstormProjects/oresoftware/suman/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:541:32)
```

the contents of exp.js are:
```js

const Threads = require('webworker-threads');

var thread = Threads.create();

const roodles = 3;

thread.eval(function () {

    console.log('roodles:', roodles);
});
```

any idea how to fix this? thanks! also, as an aside, I am not sure if I am using thread.eval() correctly, I assume by "program" a function is meant, but I am not sure how the callback will fire, can you provide an example?

**Comment by audreyt** [comment]
Try `rm -rf /Users/amills/WebstormProjects/oresoftware/suman/node_modules/webworker-threads` and then re-install with `npm i`.

As for `thread.eval`, please refer to examples/quickIntro_oneThread.js for usage.

**Comment by ORESoftware** [comment]
thanks!

**Comment by ORESoftware** [comment]
I am not sure if this is progress? :)
```

/usr/local/bin/node exp.js
/Users/Olegzandr/WebstormProjects/suman/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got **47**.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/Olegzandr/WebstormProjects/suman/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/Olegzandr/WebstormProjects/suman/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:541:32)

```

**Comment by audreyt** [comment]
Googling "Expected 48, got 47" seems to indicate that this affects a lot of modules on 6.0.0 not just us... But I could not reproduce this locally. Would upgrading to Node 6.2.1 help?

**Comment by ORESoftware** [comment]
Thanks yeah, I was trying to look that up - I am on the latest version of Node - 6.2.1, will let you know if I figure it out

**Comment by vandernorth** [comment]
Was facing the same issue, removed all node_modules, did `npm cache clean` and `npm install` which resolved the issue for me. (node 6.2.1 on windows)

**Comment by ORESoftware** [comment]
ok cool thanks
