### ISSUE TITLE
Mocha exploded on `grunt test`

### ISSUE THREAD

**Issue by kferrio** [audreyt/node-webworker-threads#119]
Not sure, but could this be related to #116 ?  I had to update `webworker` to 0.7.8 get node-gyp to build it. And there's a clue (below) that the worker pool may not be in the state that mocha needs...

```
PS C:\Users\KBF\Documents\repos\git\verb> grunt test
Running "haxe:hxml" (haxe) task

Building Haxe project...
buildjs.hxml

Running "replace:build" (replace) task

Running "concat:build" (concat) task
File build/js/verb.js created.

Running "mochaTest:test" (mochaTest) task
verb 2.0.0
= 0;
verb_Verb.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefin
ed" ? global : typeof self != "undefined" ? self : this);


    return verb;

})
>> Mocha exploded!
>> TypeError: Cannot read property 'WorkerPool' of undefined
>>     at Object.<anonymous> (C:\Users\KBF\Documents\repos\git\verb\test\testCore.js:9:9)
>>     at Module._compile (module.js:556:32)
>>     at Object.Module._extensions..js (module.js:565:10)
>>     at Module.load (module.js:473:32)
>>     at tryModuleLoad (module.js:432:12)
>>     at Function.Module._load (module.js:424:3)
>>     at Module.require (module.js:483:17)
>>     at require (internal/module.js:20:19)
>>     at C:\Users\KBF\Documents\repos\git\verb\node_modules\mocha\lib\mocha.js:220:27
>>     at Array.forEach (native)
Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by brodybits** [comment]
Sorry I don't have much experience with Grunt or Haxe. Help wanted.
