### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by johnlowvale** [audreyt/node-webworker-threads#120]
I have Visual Studio 2015, Windows SDK 8.1 & Windows SDK 10. I'm on Node JS 5.9.1.
When I tried to install webworker-threads, there's no prebuilt binary for Node JS 5.9.1 and it goes on with node-gyp but it doesn't build.

I can find stddef.h in Windows Kits/10/Include, but not found in Windows Kits/8.1/Include.
How to point node-gyp to Windows Kits/10?

`
PS D:\abi\projects\valgo\src> npm install -g webworker-threads --msvs_version=20
15

> webworker-threads@0.7.8 install d:\progs\free\nodejs-links\node_modules\webworker-threads
> node-gyp rebuild

d:\progs\free\nodejs-links\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "d:\progs\free\nvm-windows\v5.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  WebWorkerThreads.cc
**# C:\Users\johnlowvale\.node-gyp\5.9.1\include\node\v8.h(18): fatal error C1083:
Cannot open include file: 'stddef.h': No such file or directory [d:\progs\free\
nodejs-links\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\progs\free\nvm-windows\v5.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "d:\\progs\\free\\nodejs-links\\node.exe" "d:\\progs\\free\\nvm-windows\\v5.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\progs\free\nodejs-links\node_modules\webworker-threads
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "d:\\progs\\free\\nodejs-links\\node.exe" "d:\\progs\\free\\nodejs-links\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "webworker-threads" "--msvs_version=2015"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\abi\projects\valgo\src\npm-debug.log
`

**Comment by johnlowvale** [comment]
i made it finally:
- Uninstall Visual Studio
- Uninstall Windows SDK 8.1
- Uninstall Windows SDK 10
- Uninstall module windows-build-tools
- Install Visual C++ Build Tools http://landinghub.visualstudio.com/visual-cpp-build-tools
