### ISSUE TITLE
Test 20: ReferenceError: arguments_ is not defined

### ISSUE THREAD

**Issue by davisjam** [audreyt/node-webworker-threads#142]
I was going through the test suite and encountered the following failure on test 20.

```
$ node test/test20_removeAllListeners.js 
undefined:4
return thread;},this.removeAllListeners=function(e){if(arguments_.length){delete thread._on[e];}else{thread._on={};}
                                                       ^

ReferenceError: arguments_ is not defined
    at Object.thread.removeAllListeners (<anonymous>:4:56)
    at Object.<anonymous> (/home/jamie3/Desktop/node-computation/node-webworker-threads/test/test20_removeAllListeners.js:15:92)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by davisjam** [comment]
@audreyt @brodybits This test has presumably been failing for awhile. Is there a good way to run all of the tests so that we could catch this kind of thing earlier?

**Comment by audreyt** [comment]
I've made a new release so master is open to commit, feel free to add it to `npm test` — I just made you a collaborator. :-)

**Comment by davisjam** [comment]
Oooh exciting! Thanks!
