### ISSUE TITLE
Can´t install on Ubuntu 16.04 (LTS)

### ISSUE THREAD

**Issue by JPRuehmann** [audreyt/node-webworker-threads#172]
Hello
`npm i webworker-threads`
gives
```

> webworker-threads@0.7.13 install /home/ruehmann/node_modules/webworker-threads
> node-gyp rebuild

make: Verzeichnis „/home/ruehmann/node_modules/webworker-threads/build“ wird betreten
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc: In member function ‘v8::Local<v8::Value> BSONDeserializer::DeserializeDocumentInternal(bool)’:
../src/bson.cc:434:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(returnObject, name, value, v8::None);
        ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc:434:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(returnObject, name, value, v8::None);
        ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc:434:52: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(returnObject, name, value, v8::None);
                                                    ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc: In static member function ‘static void BSON::Initialize(v8::Local<v8::Object>)’:
../src/bson.cc:690:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(target, Nan::New<String>("BSON").ToLocalChecked(), t->GetFunction(), v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc:690:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(target, Nan::New<String>("BSON").ToLocalChecked(), t->GetFunction(), v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:17:0:
../src/bson.cc:690:96: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(target, Nan::New<String>("BSON").ToLocalChecked(), t->GetFunction(), v8::None);
                                                                                                ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/WebWorkerThreads.cc: In function ‘void eventLoop(typeThread*)’:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:258:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(fs_obj, "readFileSync", readFileSync_);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:258:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(fs_obj, "readFileSync", readFileSync_);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:147: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 an::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (PropertyAttribute)(DontDelete));
                                                                                                                           ^
../src/WebWorkerThreads.cc:258:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(fs_obj, "readFileSync", readFileSync_);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:259:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("native_fs_").ToLocalChecked(), fs_obj, attribute_ro_dd);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:259:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("native_fs_").ToLocalChecked(), fs_obj, attribute_ro_dd);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:259:99: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("native_fs_").ToLocalChecked(), fs_obj, attribute_ro_dd);
                                                                                                   ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:262:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "log", console_log);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:262:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "log", console_log);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:147: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 an::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (PropertyAttribute)(DontDelete));
                                                                                                                           ^
../src/WebWorkerThreads.cc:262:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "log", console_log);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:263:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "error", console_error);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(obj, Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (Property
          ^
../src/WebWorkerThreads.cc:263:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "error", console_error);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
In file included from ../src/WebWorkerThreads.cc:18:0:
../src/jslib.cc:27:147: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 an::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), (PropertyAttribute)(DontDelete));
                                                                                                                           ^
../src/WebWorkerThreads.cc:263:5: note: in expansion of macro ‘JSObjFn’
     JSObjFn(console_obj, "error", console_error);
     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:264:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("console").ToLocalChecked(), console_obj, attribute_ro_dd);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:264:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("console").ToLocalChecked(), console_obj, attribute_ro_dd);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:264:101: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("console").ToLocalChecked(), console_obj, attribute_ro_dd);
                                                                                                     ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:266:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("self").ToLocalChecked(), global, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:266:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("self").ToLocalChecked(), global, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:266:86: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("self").ToLocalChecked(), global, v8::None);
                                                                                      ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:267:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("global").ToLocalChecked(), global, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:267:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("global").ToLocalChecked(), global, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:267:88: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("global").ToLocalChecked(), global, v8::None);
                                                                                        ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:269:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("puts").ToLocalChecked(), Nan::New<FunctionTemplate>(Puts)->GetFunction(), v8::No
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:269:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("puts").ToLocalChecked(), Nan::New<FunctionTemplate>(Puts)->GetFunction(), v8::No
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:269:127: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 Nan::ForceSet(global, Nan::New<String>("puts").ToLocalChecked(), Nan::New<FunctionTemplate>(Puts)->GetFunction(), v8::None);
                                                                                                                           ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:270:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("print").ToLocalChecked(), Nan::New<FunctionTemplate>(Print)->GetFunction(), v8::
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:270:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("print").ToLocalChecked(), Nan::New<FunctionTemplate>(Print)->GetFunction(), v8::
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:270:129: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 n::ForceSet(global, Nan::New<String>("print").ToLocalChecked(), Nan::New<FunctionTemplate>(Print)->GetFunction(), v8::None);
                                                                                                                           ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:272:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("postMessage").ToLocalChecked(), Nan::New<FunctionTemplate>(postMessage)->GetFunc
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:272:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("postMessage").ToLocalChecked(), Nan::New<FunctionTemplate>(postMessage)->GetFunc
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:272:141: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 global, Nan::New<String>("postMessage").ToLocalChecked(), Nan::New<FunctionTemplate>(postMessage)->GetFunction(), v8::None);
                                                                                                                           ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:273:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("__postError").ToLocalChecked(), Nan::New<FunctionTemplate>(postError)->GetFuncti
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:273:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("__postError").ToLocalChecked(), Nan::New<FunctionTemplate>(postError)->GetFuncti
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:273:139: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
 t(global, Nan::New<String>("__postError").ToLocalChecked(), Nan::New<FunctionTemplate>(postError)->GetFunction(), v8::None);
                                                                                                                           ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:276:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("thread").ToLocalChecked(), threadObject, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:276:10: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("thread").ToLocalChecked(), threadObject, v8::None);
          ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
../src/WebWorkerThreads.cc:276:94: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
     Nan::ForceSet(global, Nan::New<String>("thread").ToLocalChecked(), threadObject, v8::None);
                                                                                              ^
In file included from ../../nan/nan.h:197:0,
                 from ../src/WebWorkerThreads.cc:12:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^
  SOLINK_MODULE(target) Release/obj.target/WebWorkerThreads.node
  COPY Release/WebWorkerThreads.node
make: Verzeichnis „/home/ruehmann/node_modules/webworker-threads/build“ wird verlassen
npm WARN saveError ENOENT: no such file or directory, open '/home/ruehmann/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ruehmann/package.json'
npm WARN ruehmann No description
npm WARN ruehmann No repository field.
npm WARN ruehmann No README data
npm WARN ruehmann No license field.

+ webworker-threads@0.7.13
added 1 package in 4.538s
```
And if I try to run `tldr`
I get
```
/usr/local/lib/node_modules/tldr/node_modules/natural/lib/natural/classifiers/classifier.js:32
    if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                       ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/build/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/build/Debug/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/build/Release/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/out/Debug/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/Debug/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/out/Release/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/Release/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/build/default/WebWorkerThreads.node
 → /usr/local/lib/node_modules/tldr/node_modules/webworker-threads/compiled/9.2.0/linux/ia32/WebWorkerThreads.node
    at bindings (/usr/local/lib/node_modules/tldr/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/tldr/node_modules/webworker-threads/index.js:1:105)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/tldr/node_modules/natural/lib/natural/classifiers/classifier.js:29:19)
```
How can I make it work?

**Comment by JPRuehmann** [comment]
Sorry my failure.
By 
```
sudo -H npm r -g webworker-threads
npm i -g webworker-threads
```
and
```
sudo -H npm r -g tldr
npm i -g tldr
```
It now works.
