### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by vtrphan** [audreyt/node-webworker-threads#189]
Hi, 
can you please fix the package for node 10
Build failed.

Thank you

**Comment by audreyt** [comment]
Hi! Would you like to provide the platform and the error log of how it failed?

**Comment by vtrphan** [comment]
```
Node 10.9.0

Log:
C:\Users\user\.node-gyp\10.9.0\include\node\v8.h(2875): note: see declaration of 'v8::String::Utf8Value::Utf8Value' (compiling source file ..\src\WebWorkerThreads.cc)
..\src\WebWorkerThreads.cc(205): error C2872: 'ArrayBufferAllocator': ambiguous symbol [C:\portal-admin\backend\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]

C:\Users\user\.node-gyp\10.9.0\include\node\v8.h(2875): note: see declaration of 'v8::String::Utf8Value::Utf8Value' (compiling source file ..\src\WebWorkerThreads.cc)
..\src\WebWorkerThreads.cc(205):  warning C4996: 'Nan::ForceSet': was declared deprecated [C:\portal-admin\backend\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
```

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\nvm\v10.9.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\nvm\\v10.9.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\arvato-projects\nmvs\nmvs-portal-admin\backend\node_modules\webworker-threads
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN ts-jest@22.4.2 requires a peer of typescript@2.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webworker-threads@0.7.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by audreyt** [comment]
Hi! Please give webworker-threads@0.7.17 a try and see if it fixes the build for you?

**Comment by vtrphan** [comment]
Hey it worked again!

Thanks a lot 👍  :)
