### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by netogerbi** [audreyt/node-webworker-threads#205]
Getting the following error on install:

warn express-setup@1.0.0 No description
153 warn express-setup@1.0.0 No repository field.
154 verbose stack Error: webworker-threads@0.7.17 install: `node-gyp rebuild`
154 verbose stack Exit status 1
154 verbose stack     at EventEmitter.<anonymous> (/home/netogerbi/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
154 verbose stack     at EventEmitter.emit (events.js:193:13)
154 verbose stack     at ChildProcess.<anonymous> (/home/netogerbi/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
154 verbose stack     at ChildProcess.emit (events.js:193:13)
154 verbose stack     at maybeClose (internal/child_process.js:999:16)
154 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
155 verbose pkgid webworker-threads@0.7.17
156 verbose cwd /home/netogerbi/workspaces/nodejs/node-advanced-concepts/pm2-tests
157 verbose Linux 4.9.0-11-amd64
158 verbose argv "/usr/bin/node" "/home/netogerbi/.npm-global/bin/npm" "install" "--save" "webworker-threads"
159 verbose node v11.15.0
160 verbose npm  v6.12.0
161 error code ELIFECYCLE
162 error errno 1
163 error webworker-threads@0.7.17 install: `node-gyp rebuild`
163 error Exit status 1
164 error Failed at the webworker-threads@0.7.17 install script.
164 error This is probably not a problem with npm. There is likely additional logging output above.
165 verbose exit [ 1, true ]

On debian 9...

**Comment by chriskirchner** [comment]
My debian 10 build caught on fire too
