### ISSUE TITLE
Can't install on macOS Catalina

### ISSUE THREAD

**Issue by saurabh0227** [audreyt/node-webworker-threads#206]
webworker-threads@0.7.17 install /Users/saurabhkumar/Desktop/Node/advance_node/section_2/node_modules/webworker-threads
> node-gyp rebuild

  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:140:90: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteLengthPrefixedString(const Local<String>& value)   { count += value->Utf8Length()+5; }
                                                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:142:80: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteString(const Local<String>& value)                                 { count += value->Utf8Length() + 1; }   // This return...
                                                                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:165:92: error: no matching member function for call to 'Get'
    void        WriteByte(const Local<Object>& object, const Local<String>& key)        { *p++ = object->Get(key)->Int32Value(); }
                                                                                                 ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:175:83: error: too few arguments to function call, single argument 'isolate' was not specified
    void        WriteBool(const Local<Value>& value)                                    { WriteByte(value->BooleanValue() ? 1 : 0); }
                                                                                                    ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2771:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:176:83: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteInt32(const Local<Value>& value)                                   { WriteInt32(value->Int32Value());                      }
                                                                                                     ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2778:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:177:97: error: no matching member function for call to 'Get'
    void        WriteInt32(const Local<Object>& object, const Local<String>& key) { WriteInt32(object->Get(key)); }
                                                                                               ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:178:85: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteInt64(const Local<Value>& value)                                   { WriteInt64(value->IntegerValue());            }
                                                                                                     ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2774:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:179:86: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteDouble(const Local<Value>& value)                                  { WriteDouble(value->NumberValue());            }
                                                                                                      ~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2773:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:180:99: error: no matching member function for call to 'Get'
    void        WriteDouble(const Local<Object>& object, const Local<String>& key) { WriteDouble(object->Get(key)); }
                                                                                                 ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:182:92: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteLengthPrefixedString(const Local<String>& value)   { WriteInt32(value->Utf8Length()+1); WriteString(value); }
                                                                                     ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:184:76: error: too few arguments to function call, expected at least 2, have 1
        void    WriteString(const Local<String>& value)                                 { p += value->WriteUtf8(p); }           // This return...
                                                                                               ~~~~~~~~~~~~~~~~  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2947:3: note: 'WriteUtf8' declared here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:51:10: error: no matching member function for call to 'Get'
        object->Get(key)->ToString()->Write(buffer, 0, 12);
        ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:71:41: error: too few arguments to function call, single argument 'isolate' was not specified
        size_t keyLength = keyName->Utf8Length();
                           ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:77:36: error: too few arguments to function call, expected at least 2, have 1
        keyName->WriteUtf8(keyStringBuffer);
        ~~~~~~~~~~~~~~~~~~                ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2947:3: note: 'WriteUtf8' declared here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:103:40: error: no matching member function for call to 'GetPropertyNames'
  Local<Array> propertyNames = object->GetPropertyNames();
                               ~~~~~~~~^~~~~~~~~~~~~~~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3702:43: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3704:43: note: candidate function not viable: requires at least 4 arguments, but
      0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:109:54: error: no matching member function for call to 'Get'
                const Local<String>& propertyName = propertyNames->Get(i)->ToString();
                                                    ~~~~~~~~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:112:47: error: no matching member function for call to 'Get'
                const Local<Value>& propertyValue = object->Get(propertyName);
                                                    ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:130:58: error: too few arguments to function call, single argument 'context' was not specified
        Local<Array> array = Local<Array>::Cast(value->ToObject());
                                                ~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2754:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:137:39: error: no matching member function for call to 'Get'
                SerializeValue(typeLocation, array->Get(i));
                                             ~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/saurabhkumar/Desktop/Node/advance_node/section_2/node_modules/webworker-threads
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN section_2@1.0.0 No description
npm WARN section_2@1.0.0 No repository field.

saurabhkumar@Saurabhs-MacBook-Pro section_2 % sudo npm i webworker-threads --save
Password:

> webworker-threads@0.7.17 install /Users/saurabhkumar/Desktop/Node/advance_node/section_2/node_modules/webworker-threads
> node-gyp rebuild

  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:140:90: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteLengthPrefixedString(const Local<String>& value)   { count += value->Utf8Length()+5; }
                                                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:142:80: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteString(const Local<String>& value)                                 { count += value->Utf8Length() + 1; }   // This return...
                                                                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:165:92: error: no matching member function for call to 'Get'
    void        WriteByte(const Local<Object>& object, const Local<String>& key)        { *p++ = object->Get(key)->Int32Value(); }
                                                                                                 ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:175:83: error: too few arguments to function call, single argument 'isolate' was not specified
    void        WriteBool(const Local<Value>& value)                                    { WriteByte(value->BooleanValue() ? 1 : 0); }
                                                                                                    ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2771:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:176:83: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteInt32(const Local<Value>& value)                                   { WriteInt32(value->Int32Value());                      }
                                                                                                     ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2778:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:177:97: error: no matching member function for call to 'Get'
    void        WriteInt32(const Local<Object>& object, const Local<String>& key) { WriteInt32(object->Get(key)); }
                                                                                               ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:178:85: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteInt64(const Local<Value>& value)                                   { WriteInt64(value->IntegerValue());            }
                                                                                                     ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2774:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:179:86: error: too few arguments to function call, single argument 'context' was not specified
    void        WriteDouble(const Local<Value>& value)                                  { WriteDouble(value->NumberValue());            }
                                                                                                      ~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2773:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:180:99: error: no matching member function for call to 'Get'
    void        WriteDouble(const Local<Object>& object, const Local<String>& key) { WriteDouble(object->Get(key)); }
                                                                                                 ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:182:92: error: too few arguments to function call, single argument 'isolate' was not specified
        void    WriteLengthPrefixedString(const Local<String>& value)   { WriteInt32(value->Utf8Length()+1); WriteString(value); }
                                                                                     ~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
In file included from ../src/bson.cc:41:
../src/bson.h:184:76: error: too few arguments to function call, expected at least 2, have 1
        void    WriteString(const Local<String>& value)                                 { p += value->WriteUtf8(p); }           // This return...
                                                                                               ~~~~~~~~~~~~~~~~  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2947:3: note: 'WriteUtf8' declared here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:51:10: error: no matching member function for call to 'Get'
        object->Get(key)->ToString()->Write(buffer, 0, 12);
        ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:71:41: error: too few arguments to function call, single argument 'isolate' was not specified
        size_t keyLength = keyName->Utf8Length();
                           ~~~~~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2887:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:77:36: error: too few arguments to function call, expected at least 2, have 1
        keyName->WriteUtf8(keyStringBuffer);
        ~~~~~~~~~~~~~~~~~~                ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2947:3: note: 'WriteUtf8' declared here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
  ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:103:40: error: no matching member function for call to 'GetPropertyNames'
  Local<Array> propertyNames = object->GetPropertyNames();
                               ~~~~~~~~^~~~~~~~~~~~~~~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3702:43: note: candidate function not viable: requires single argument 'context',
      but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3704:43: note: candidate function not viable: requires at least 4 arguments, but
      0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:109:54: error: no matching member function for call to 'Get'
                const Local<String>& propertyName = propertyNames->Get(i)->ToString();
                                                    ~~~~~~~~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:112:47: error: no matching member function for call to 'Get'
                const Local<Value>& propertyValue = object->Get(propertyName);
                                                    ~~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:130:58: error: too few arguments to function call, single argument 'context' was not specified
        Local<Array> array = Local<Array>::Cast(value->ToObject());
                                                ~~~~~~~~~~~~~~~ ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:2754:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/WebWorkerThreads.cc:17:
../src/bson.cc:137:39: error: no matching member function for call to 'Get'
                SerializeValue(typeLocation, array->Get(i));
                                             ~~~~~~~^~~
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/saurabhkumar/Library/Caches/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/saurabhkumar/Desktop/Node/advance_node/section_2/node_modules/webworker-threads
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN section_2@1.0.0 No description
npm WARN section_2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webworker-threads@0.7.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webworker-threads@0.7.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saurabhkumar/.npm/_logs/2020-04-24T18_15_17_865Z-debug.log

**Comment by PiotrNap** [comment]
I'm getting the same issue! Couldn't find any solution yet...

**Comment by audreyt** [comment]
Hi! Please check if https://www.npmjs.com/package/web-worker works for your purpose — I'm considering deprecating this module in favor of the new one from @developit.
