### ISSUE TITLE
Failed to install webworker-threads@0.7.17 using npm

### ISSUE THREAD

**Issue by 4nkitpatel** [audreyt/node-webworker-threads#208]
Error Log
I am in Linux , Ubuntu

```
In file included from ../src/WebWorkerThreads.cc:16:
../src/queues_a_gogo.cc:153:13: warning: ‘void initQueues()’ defined but not used [-Wunused-function]
  153 | static void initQueues (void) {
      |             ^~~~~~~~~~
make: *** [WebWorkerThreads.target.mk:109: Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
make: Leaving directory '/home/sh4d0w/Desktop/Node-Advance/node_modules/webworker-threads/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sh4d0w/Desktop/Node-Advance/node_modules/webworker-threads
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN node-advance@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webworker-threads@0.7.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webworker-threads@0.7.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sh4d0w/.npm/_logs/2020-05-22T13_56_47_894Z-debug.log
```

**Comment by joules457** [comment]
Seem i have the same problem too

```
In file included from ../src/WebWorkerThreads.cc:16:0:
../src/queues_a_gogo.cc:153:13: warning: ‘void initQueues()’ defined but not used [-Wunused-function]
 static void initQueues (void) {
             ^~~~~~~~~~
WebWorkerThreads.target.mk:109: recipe for target 'Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o' failed
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
make: Leaving directory '/home/joules/workspace/test/node_modules/webworker-threads/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-62-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/joules/workspace/test/node_modules/webworker-threads
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webworker-threads@0.7.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webworker-threads@0.7.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joules/.npm/_logs/2020-07-06T22_39_15_227Z-debug.log

```

Im in Ubuntu 18.04 using ` Linux 5.3.0-62-generic` kernel. Always display node-gyp -v v5.1.0 altough i installed node-gyp v7.0.0 globally.

**Comment by langyuxiansheng** [comment]
我也有同样的问题

**Comment by polyzer** [comment]
I have same problem.

**Comment by d00rsfan** [comment]
sudo npm install node-gyp@latest -g
npm install --save webworker-threads
the same error
It's seem's package is obsolete and abandoned.

**Comment by pimpannt** [comment]
Me too, I got the same

**Comment by ayuthmang** [comment]
I face the problem too, solved by using the node version 8 then npm install would be fine.

**Comment by EiskalterFreund** [comment]
I have the problem too

**Comment by audreyt** [comment]
A pull request to cap supported node version and suggest an alternative for newer nodes (with built-in workers) would be very much appreciated.

**Comment by airlenet** [comment]
Can you provide a version connected to node 10 +

> A pull request to cap supported node version and suggest an alternative for newer nodes (with built-in workers) would be very much appreciated.

**Comment by gitmurali** [comment]
same problem I'm using Node v16.x.x

**Comment by Ranjan1501** [comment]
same problem I am using v20 on mac m1 , tried with` npm install `instead of `npm i ` but same result.
