### ISSUE TITLE
build failed when using io.js 1.0.4 and node v0.11.16

### ISSUE THREAD

**Issue by gitawego** [audreyt/node-webworker-threads#45]
the build is failed when using latest io.js and node.js
```shell
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
../src/WebWorkerThreads.cc:291:5: error: no matching member function for call to 'Set'
    JSObjFn(fs_obj, "readFileSync", readFileSync_);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:292:13: error: no matching member function for call to 'Set'
    global->Set(NanNew<String>("native_fs_"), fs_obj, attribute_ro_dd);
    ~~~~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:295:5: error: no matching member function for call to 'Set'
    JSObjFn(console_obj, "log", console_log);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:296:5: error: no matching member function for call to 'Set'
    JSObjFn(console_obj, "error", console_error);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:297:13: error: no matching member function for call to 'Set'
    global->Set(NanNew<String>("console"), console_obj, attribute_ro_dd);
    ~~~~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:345:17: error: no member named 'IdleNotification' in 'v8::V8'
            V8::IdleNotification();
            ~~~~^
../src/WebWorkerThreads.cc:430:17: error: no member named 'IdleNotification' in 'v8::V8'
            V8::IdleNotification();
            ~~~~^
7 errors generated.
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gitawego/.nvm/v0.11.16/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/gitawego/.nvm/v0.11.16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gitawego/workspace/audit-server/node_modules/webworker-threads
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

**Comment by audreyt** [comment]
Hi, can you try the latest HEAD (which I just pushed) and see if `nan 1.6.0` fixes some of it?

**Comment by gitawego** [comment]
same error, btw, I'm using mac os yosemite
```
> webworker-threads@0.5.4 install /Users/gitawego/workspace/test/node-webworker-threads
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
../src/WebWorkerThreads.cc:281:24: warning: 'NanNewContextHandle' is deprecated [-Wdeprecated-declarations]
        Local<Context> ctx =  NanNewContextHandle(NULL, otmpl);
                              ^
../node_modules/nan/nan.h:589:52: note: 'NanNewContextHandle' has been explicitly marked deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::Context> NanNewContextHandle(
                                                   ^
../src/WebWorkerThreads.cc:291:5: error: no matching member function for call to 'Set'
    JSObjFn(fs_obj, "readFileSync", readFileSync_);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:292:13: error: no matching member function for call to 'Set'
    global->Set(NanNew<String>("native_fs_"), fs_obj, attribute_ro_dd);
    ~~~~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:295:5: error: no matching member function for call to 'Set'
    JSObjFn(console_obj, "log", console_log);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:296:5: error: no matching member function for call to 'Set'
    JSObjFn(console_obj, "error", console_error);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jslib.cc:25:7: note: expanded from macro 'JSObjFn'
        obj->Set(NanNew<String>(name), NanNew<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
        ~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:297:13: error: no matching member function for call to 'Set'
    global->Set(NanNew<String>("console"), console_obj, attribute_ro_dd);
    ~~~~~~~~^~~
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/gitawego/.node-gyp/0.11.16/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/WebWorkerThreads.cc:345:13: error: no member named 'IdleNotification' in 'v8::V8'; did you mean 'NanIdleNotification'?
            V8::IdleNotification();
            ^~~~~~~~~~~~~~~~~~~~
            NanIdleNotification
../node_modules/nan/nan.h:186:19: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
                  ^
../src/WebWorkerThreads.cc:345:34: error: too few arguments to function call, single argument 'idle_time_in_ms' was not specified
            V8::IdleNotification();
            ~~~~~~~~~~~~~~~~~~~~ ^
../node_modules/nan/nan.h:186:3: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
  ^
../node_modules/nan/nan.h:39:21: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE inline __attribute__((always_inline))
                    ^
../src/WebWorkerThreads.cc:430:13: error: no member named 'IdleNotification' in 'v8::V8'; did you mean 'NanIdleNotification'?
            V8::IdleNotification();
            ^~~~~~~~~~~~~~~~~~~~
            NanIdleNotification
../node_modules/nan/nan.h:186:19: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
                  ^
../src/WebWorkerThreads.cc:430:34: error: too few arguments to function call, single argument 'idle_time_in_ms' was not specified
            V8::IdleNotification();
            ~~~~~~~~~~~~~~~~~~~~ ^
../node_modules/nan/nan.h:186:3: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
  ^
../node_modules/nan/nan.h:39:21: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE inline __attribute__((always_inline))
                    ^
In file included from ../src/WebWorkerThreads.cc:13:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:209:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/WebWorkerThreads.cc:900:44: note: in instantiation of function template specialization 'NanNew<v8::Integer, long>' requested here
    local_JSObject->Set(NanNew(id_symbol), NanNew<Integer>(thread->id));
                                           ^
../node_modules/nan/nan_new.h:109:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:110:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
1 warning and 10 errors generated.
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
```

**Comment by audreyt** [comment]
OK. I did some early work in `iojs` branch but didn't quite finish it — people versed in C++ are welcome to pick this up.

**Comment by gitawego** [comment]
I've tested with the unstable version of nodeJs, It doesn't work neither. 
so if Node v0.12 released, the current version won't work neither.

**Comment by Samreay** [comment]
Has there been any update to adding io.js support in?

**Comment by brodybits** [comment]
I have tested the latest version with Node 0.11.16 and io.js 1.0.4, as well as Node 0.10.40, 0.12.7, 4.0.0, and 4.1.1. Others have fixed and tested with io.js 2.0.0 and 3.3.1. Closing.

**Comment by brodybits** [comment]
Support for io.js 1.0.x is now explicitly marked in CHANGES.md (I tested the old version).
