### ISSUE TITLE
Build failing on Mac OSX Yosemite / io.js 1.8.1

### ISSUE THREAD

**Issue by Lokeh** [audreyt/node-webworker-threads#55]
I can't tell if this is a problem with node-gyp, or node-webworker-threads.

Here is the relevant log:

```
> webworker-threads@0.5.5 install /Users/will/Code/happy/node_modules/webworker-threads
> node-gyp rebuild

WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/will/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/will/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/will/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/will/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/will/Code/happy/node_modules/webworker-threads
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/will/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/will/.nvm/versions/io.js/v1.8.1/bin/npm" "install" "webworker-threads"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.4
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.5.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webworker-threads@0.5.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/will/Code/happy/npm-debug.log
```

My googling has shown that this might be an issue with the latest versions of node and io and node-gyp, although I have seen other packages that have submitted fixes for similar issues.

**Comment by heavyk** [comment]
this is a failure in the way node-gyp finds what "node" you're using. you can fix this by linking the fixed node-gyp instead (like this):
```
cd /Users/will/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp
npm link
```

now you should be able to run node-gyp rebuild fine
