### ISSUE TITLE
"npm install webworker-threads" fails due to libcpmt.lib

### ISSUE THREAD

**Issue by AArnott** [audreyt/node-webworker-threads#85]
Installing this package worked a week ago. Now (on a similar machine) it doesn't.

> LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\git\WebWorker\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]

The full output is:

```
npm install  webworker-threads
-
> webworker-threads@0.6.2 install C:\git\WebWorker\node_modules\webworker-threads
> node-gyp rebuild


C:\git\WebWorker\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
  WebWorkerThreads.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enable
d. Specify /EHsc [C:\git\WebWorker\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
c:\git\webworker\node_modules\webworker-threads\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'int64_t' to 'double', possibl
e loss of data [C:\git\WebWorker\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
          c:\git\webworker\node_modules\webworker-threads\src\bson.cc(560) : see reference to function template instantiation 'v8::Local<v8::Number> Nan::N
  ew<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\git\WebWorker\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\WebWorker\node_modules\webworker-threads
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "webworker-threads"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.6.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\WebWorker\npm-debug.log
```

**Comment by audreyt** [comment]
Maybe it's outdated npm or environment settings?

http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64
http://stackoverflow.com/questions/18890801/link-fatal-error-lnk1104-cannot-open-file-libcpmt-lib-after-manually-config
https://github.com/nodejs/node-gyp/issues/555
